#docker-compose up -d
version: '3.1'
services:
  post-db:
    image: 'postgres'
    restart: always
    networks: krealtors-net
    ports:
      - 5432:5432
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=1qaz2wsx!!
  # mongo-db:
  #   image: mongo
  #   restart: always
  #   networks: krealtors-net
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - 'mongodb_data:/data/db'
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongoadmin
  #     MONGO_INITDB_ROOT_PASSWORD: 1qaz2wsx!!
  
  realtor-service:
    image: realtor
    restart: always
    networks: krealtors-net
    depends_on:
      - post-db
    environment:
      - DB_TYPE = mongodb
      - DB_USER = krealor
      - DB_PASSWORD = 1qaz2wsx!!
      - DB_HOST = cluster0.oh1rc.mongodb.net/myFirstDatabase
      - DB_PORT = 27017
      - DATABASE = krealtor
      - DB_MAX_IDLE_CONNS = 10
      - DB_MAX_OPEN_CONNS = 10
      - LOG_LEVEL = info
      - BIND_PORT = 9003

  gateway:
    image: gateway
    restart: always
    networks: krealtors-net
    depends_on:
      - post-db
      - realtor-service
    ports:
      - 9000:9000
    environment:
      - USER_ENDPOINT = user-service:9001
      - REGION_ENDPOINT = region-service:9002
      - REALTOR_ENDPOINT = realtor-service:9003

volumes:
  postgresql_data:

networks:
  krealtors-net:

#EC2 AWS
#sudo yum -y install docker
#sudo systemctl start docker
#docker-compose 설치하기
# sudo curl -L https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
# sudo chmod +x /usr/local/bin/docker-compose
# docker-compose --version 
#docker login // coolnice 1qaz2wsx!!
#sudo chmod 666 /var/run/docker.sock