#docker-compose up -d
version: '3.1'
services:
  post-db:
    image: 'postgres'
    restart: always
    networks: krealtors-net
    ports:
      - 5432:5432
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=1qaz2wsx!!
  # mongo-db:
  #   image: mongo
  #   restart: always
  #   networks: krealtors-net
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - 'mongodb_data:/data/db'
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: mongoadmin
  #     MONGO_INITDB_ROOT_PASSWORD: 1qaz2wsx!!
  gateway:
    image: gateway
    restart: always
    networks: krealtors-net
    depends_on:
      - post-db
      #- mongo-db
    ports:
      - 9000:9000

  realtor-service:
    image: realtor
    restart: always
    networks: krealtors-net
    depends_on:
      - post-db
    
    
volumes:
  postgresql_data:

networks:
  krealtors-net:

#EC2 AWS
#sudo yum -y install docker
#sudo systemctl start docker
#docker-compose 설치하기
# sudo curl -L https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
# sudo chmod +x /usr/local/bin/docker-compose
# docker-compose --version 
#docker login // coolnice 1qaz2wsx!!
#sudo chmod 666 /var/run/docker.sock