#docker-compose up -d
version: '3.1'
services:
  postgresql:
    image: 'postgres'
    restart: always
    ports:
      - 5432:5432
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=1qaz2wsx!!
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - 'mongodb_data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: 1qaz2wsx!!
  
volumes:
  postgresql_data:
  mongodb_data:



#EC2 AWS
#sudo yum -y install docker
#sudo systemctl start docker
#docker-compose 설치하기
# sudo curl -L https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
# sudo chmod +x /usr/local/bin/docker-compose
# docker-compose --version 
#docker login // coolnice 1qaz2wsx!!
#sudo chmod 666 /var/run/docker.sock